# -*- mode: ruby -*-
# vi: set ft=ruby :

RAM = 1024
CPU = 1

Vagrant.configure("2") do |config|
  config.vm.box = "Vince0169/nginx"
  config.vm.network "private_network", ip: "10.0.0.10"
  config.vm.synced_folder "/static-website-example", "/usr/share/nginx/html/"
  config.vm.provider "virtualbox" do |v|
    v.memory = RAM
    v.cpus = CPU
  end	
end
